import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ignoredDirectories = new Set([".git", "node_modules", "test"]);
const textExtensions = new Set([".md", ".mjs", ".js", ".json", ".yaml", ".yml", ".gitignore"]);

function sourceFiles(directory) {
  const files = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (ignoredDirectories.has(entry.name)) continue;
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...sourceFiles(fullPath));
    else if (entry.isFile() && textExtensions.has(path.extname(entry.name))) files.push(fullPath);
  }
  return files;
}

test("repository contains no private workspace data or generation markers", () => {
  const forbidden = [
    /\/Users\/woongjaekim/,
    /CravingCollector/,
    /Collectiv Work System/,
    /Generated by (?:AI|ChatGPT|Claude|Codex)/i,
    /AI-generated/i,
    /Co-authored-by:/i,
    /\[TODO:/
  ];

  for (const filePath of sourceFiles(repositoryRoot)) {
    const content = fs.readFileSync(filePath, "utf8");
    for (const pattern of forbidden) {
      assert.doesNotMatch(content, pattern, `${path.relative(repositoryRoot, filePath)} matched ${pattern}`);
    }
  }
});

test("English and Korean readmes provide complete setup paths", () => {
  const english = fs.readFileSync(path.join(repositoryRoot, "README.md"), "utf8");
  const korean = fs.readFileSync(path.join(repositoryRoot, "README.ko.md"), "utf8");
  const requiredCommands = [
    "npm install --global github:hawoond/productloom",
    "productloom init",
    "productloom new brief",
    "productloom new screen",
    "productloom validate --mode strict",
    "productloom migrate --from cws",
    "codex plugin marketplace add hawoond/productloom --ref main",
    "codex plugin add productloom@productloom"
  ];

  assert.match(english, /\[한국어\]\(README\.ko\.md\)/);
  assert.match(korean, /\[English\]\(README\.md\)/);

  for (const command of requiredCommands) {
    assert.ok(english.includes(command), `README.md is missing ${command}`);
    assert.ok(korean.includes(command), `README.ko.md is missing ${command}`);
  }

  const packageMetadata = JSON.parse(
    fs.readFileSync(path.join(repositoryRoot, "package.json"), "utf8")
  );
  assert.ok(packageMetadata.files.includes("README.ko.md"));
});
