import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ignoredDirectories = new Set([".git", "node_modules", "test"]);
const textExtensions = new Set([".md", ".mjs", ".js", ".json", ".yaml", ".yml", ".gitignore"]);

function sourceFiles(directory) {
  const files = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (ignoredDirectories.has(entry.name)) continue;
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...sourceFiles(fullPath));
    else if (entry.isFile() && textExtensions.has(path.extname(entry.name))) files.push(fullPath);
  }
  return files;
}

test("repository contains no private workspace data or generation markers", () => {
  const forbidden = [
    /\/Users\/woongjaekim/,
    /CravingCollector/,
    /Collectiv Work System/,
    /Generated by (?:AI|ChatGPT|Claude|Codex)/i,
    /AI-generated/i,
    /Co-authored-by:/i,
    /\[TODO:/
  ];

  for (const filePath of sourceFiles(repositoryRoot)) {
    const content = fs.readFileSync(filePath, "utf8");
    for (const pattern of forbidden) {
      assert.doesNotMatch(content, pattern, `${path.relative(repositoryRoot, filePath)} matched ${pattern}`);
    }
  }
});
